---
title: '파이선 기초문법2+Numpy'

date: '2022-06-28'

---

##복습-반복문 연습
- for loop and while loop


In [ ]:
for i in range(3):
  print("Hellow World")
  print("안녕하세요")  

Hellow World
안녕하세요
Hellow World
안녕하세요
Hellow World
안녕하세요


In [ ]:
for i in range(100):
  print("No:",i+1)
  if i == 10 :
     break
  print("Hellow World")
  print("안녕하세요")

No: 1
Hellow World
안녕하세요
No: 2
Hellow World
안녕하세요
No: 3
Hellow World
안녕하세요
No: 4
Hellow World
안녕하세요
No: 5
Hellow World
안녕하세요
No: 6
Hellow World
안녕하세요
No: 7
Hellow World
안녕하세요
No: 8
Hellow World
안녕하세요
No: 9
Hellow World
안녕하세요
No: 10
Hellow World
안녕하세요
No: 11


In [ ]:
"k" in "kaggle"
if "k" == "a":
  print("출력이 되나요?")
else:
  print("출력이 안됨")

출력이 안됨


In [69]:
a = "Kaggle"

for i in a:
  print(i)
  if i == "a":
    break

K
a


- 리스트의 값이 존재
- 전체 총합구하기

In [64]:
numbers = [3,2,3,4,5]
sum = 0

for num in numbers:
  print("number:",num)
  sum = sum + num
  print("total:",sum)

print("-----최종결괏값------")
print(sum)  

number: 3
total: 3
number: 2
total: 5
number: 3
total: 8
number: 4
total: 12
number: 5
total: 17
-----최종결괏값------
17


In [ ]:
fruits = ['apple', 'kiwi', 'mango']
newlist = []
# apple : a가 있나요? 있으면 newlist에 추가하세요
# kiwi에는 a가 있나요 없으면 그냥 넘어가요
# mango : a가 있나요? 그럼 newlist에 추가하세요

for fruit in fruits:
  print("조건문 밖:", fruit)
  if "a" in fruit:
    print("조건문 안:",fruit)
    newlist.append(fruit)

print(newlist)

조건문 밖: apple
조건문 안: apple
조건문 밖: kiwi
조건문 밖: mango
조건문 안: mango
['apple', 'mango']


## While Loop
- 분석할 때는 거의 사용안되고 개발할 때 사용

In [ ]:
i=1
while i<10: #조건식 :참일때만 반복문 코드가 돔 (무한루프가 될 수 있다)
  # 코드 
  print(i)
  i+=1 #1씩 증감 하여 10이 되면 거짓이 되면 멈춤
  #1-=1 #1씩 감소

1
2
3
4
5
6
7
8
9


## 사용자 정의 함수
- 내가 필요에 의해 직접 함수를 작성
- 함수 문서화
 + 키워드 : Docsting ->""" 내용 """ 
 + 함수에는 반드시 설명이 들어가야 된다.
 + ***오늘 배운 것 중에 두번째로 중요한 내용!!!***


In [ ]:
def 함수명(param1, param2):
  #코드
  return None

In [ ]:
def add(a = 0,b = 1):
  # c = a + b
  # return c
  return a + b

print(add(a = 5, b = 4))
print(add())  

9
1


- 사칙연산 사용자 정의 함수 만들기

In [65]:
def de(a, b) :
  return a + b
print(de(1,2))
def bbe(a, b) :
  return a - b
print(bbe(1,2))
def kop(a, b) :
  return a * b
print(kop(1,2))
def na(a, b) :
  return a / b
print(na(1,2))
def mean(a , b):
  return (a + b) / 2
print(mean(5,10))

3
-1
2
0.5
7.5


In [68]:
a = int(input('첫번째수를 넣으세요'))
b = int(input('두번째수를 넣으세요'))
def mean (a, b):
  return (a + b)/2

print(mean(a,b))

첫번째수를 넣으세요5
두번째수를 넣으세요10
7.5


In [40]:
def subtract(a, b):
  """ a,b를 빼는 함수

  parameters:
  a(int): int형 숫자 a가 입력
  
  b(int): int형 숫자 b가 입력

  return:
    int :반환값
  """
  return a-b

print(subtract(a= 5, b= 10))
print(subtract.__doc__)

-5
 a,b를 빼는 함수

  parameters:
  a(int): int형 숫자 a가 입력
  
  b(int): int형 숫자 b가 입력

  return:
    int :반환값
  


## Numpy
- 내장 모듈(=라이브러리=R의 패키지)이 아닌 별도 라이브러리를 설치해야 함
- 별도 라이브러리 설치가 필요(구글코랩은 불필요)


In [42]:
import numpy as np
print(np.__version__)

1.21.6


In [63]:
temp = [1,2,3]
temp_array = np.array(temp) # 리스트를 배열로 변환

print (temp_array)
print (type(temp_array))

[1 2 3]
<class 'numpy.ndarray'>


## 사칙연산

In [45]:
math_score = [90, 80, 100]
eng_score= [80, 90,100]

#print(math_score+eng_score)
math_array = np.array(math_score)
eng_array= np.array(eng_score)

total= math_array + eng_array
print(total)
print(type(total))


[170 170 200]
<class 'numpy.ndarray'>


## 집계함수

In [61]:
print(np.min(total))
print(np.max(total))
print(np.sum(total))

170
200
540


## 차원 확인
- 배열의 차원 확인 필요

In [53]:
# 1차원 배열 생성
temp_arr= np.array([1,2,3])
print(temp_arr.shape)
print(temp_arr.ndim) #차원을 나타냄
print(temp_arr)

(3,)
1
[1 2 3]


In [54]:
# 2차원 배열 생성
temp_arr = np.array([[1,2,3],[4,5,6]])
print(temp_arr.shape)
print(temp_arr.ndim) #차원을 나타냄
print(temp_arr)

(2, 3)
2
[[1 2 3]
 [4 5 6]]


In [60]:
# 3차원 배열-> 이미지
temp_arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(temp_arr.shape)
print(temp_arr.ndim)
print(temp_arr)

(2, 2, 3)
3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 배열 생성의 다양한 방법들
- 모두 0으로 채운다


In [1]:
import numpy as np 
print(np.__version__)

1.21.6


In [29]:
temp_arr = np.zeros((4,2,3))
temp_arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

- 모두 1로 채운다.

In [6]:
temp_arr = np.ones((2,3))
temp_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

- 임의의 상수값으로 채운다(3개의 1행 3열자료에 100을 넣었다)
3x1x3배열이라고 말한다.

In [61]:
temp_arr = np.full((3,3),100.1)
temp_arr

array([[100.1, 100.1, 100.1],
       [100.1, 100.1, 100.1],
       [100.1, 100.1, 100.1]])

 - 2개의 3행 4열 자료에 100을 넣었다.

In [60]:
temp_arr = np.full((2,3,4),100)
temp_arr

array([[[100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]]])

- 최소, 최대 숫자의 범위를 정해두고,각 구간별로 값을 생성
- .linspace(시작값, 종료값, 간격수)

In [31]:
temp_arr = np.linspace(5,10,8)
temp_arr

array([ 5.        ,  5.71428571,  6.42857143,  7.14285714,  7.85714286,
        8.57142857,  9.28571429, 10.        ])

- 반복문 시 , 자주 등장하는 배열

In [10]:
temp_arr = np.arange(1,11,1)
temp_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 난수 생성

In [12]:
from numpy import random
x = random.rand()
print(x)

0.09081438142620213


In [13]:
import numpy
x = numpy.random.rand()
print(x)

0.17530497899866515


- 위의 두가지는 같은 내용이다.랜덤함수의 위치를 명시해준다.

- 랜덤 정수값 추출

In [16]:
from numpy import random
#x = random.randint(100, size = (5))
x = random.randint(100, size = (3,5))
print(x)
print(type(x))

[[ 4 26 62 97 49]
 [68 51 15 95 55]
 [37 91 98 47  8]]
<class 'numpy.ndarray'>


In [38]:
from numpy import random
#x = random.randint(100, size = (5))
x = random.randint(100, size = (3,2,4))
print(x)
print(type(x))

[[[10 16  7 84]
  [49 15 85 24]]

 [[78 15 34 79]
  [95 66 42 17]]

 [[69  9  8  4]
  [41 78 93 37]]]
<class 'numpy.ndarray'>


- 랜덤 배열  실숫값 추출

In [17]:
from numpy import random
x = random.rand(2,5)
print(x)
print(type(x))

[[0.4704299  0.23477923 0.28244335 0.71846304 0.75368955]
 [0.41210023 0.91448093 0.15992748 0.33859588 0.52543335]]
<class 'numpy.ndarray'>


## Numpy 사칙 연산

In [18]:
import numpy as np
array_01 = np.array([1,2,3])
array_02 = np.array([10,20,30])

In [28]:
# 덧셈
newArr = np.add(array_01,array_02)
print(newArr)

# 뺄셈
newArr = np.subtract(array_01,array_02)
print(newArr)

# 곱셈
newArr = np.multiply(array_01,array_02)
print(newArr)

# 나눗셈
newArr = np.divide(array_01,array_02)
print(newArr)

# 거듭제곱
array_01 = np.array([1,2,3])
array_02 = np.array([2,4,2])
newArr = np.power(array_01,array_02)
print(newArr)

[11 22 33]
[ -9 -18 -27]
[10 40 90]
[0.1 0.1 0.1]
[ 1 16  9]


## 소숫점 정렬
- 소숫점을 정렬하는 다양한 방법

In [41]:
# 소숫점 제거
import numpy as np
temp_arr =np.trunc([-1.91,1.9])
print(temp_arr)
      
temp_arr =np.fix([-1.23,1.9])
print(temp_arr)

[-1.  1.]
[-1.  1.]


In [23]:
# 임의의 소숫점 자리에서 반올림
temp_arr = np.around([-1.2345667,1.23232323],5)
print(temp_arr)

[-1.23457  1.23232]


In [25]:
#소숫점 모두 내림
temp_arr = np.floor([-1.2345667,1.23232323])
print(temp_arr)

[-2.  1.]


In [26]:
#소숫점 모두 올림
temp_arr = np.ceil([-1.2345667,1.23232323])
print(temp_arr)

[-1.  2.]


## 조건식
 - pandas 가공
 - numpy
 - 조건식
  + 하나(단일)의 조건식(->np.where)
  + 다중 조건식(***이번 시간에 가장 중요함!!!!***)

In [43]:
temp_arr = np.arange(10)
temp_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
# 5보다 작으면 원 값 유지
# 5보다 크면 곱하기 10을 유지해줌

In [46]:
#np.where(조건식, 참일 때, 거짓일 때)
np.where(temp_arr< 5, temp_arr, temp_arr*10)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [47]:
temp_arr = np.arange(10)
# temp_arr
cond_list = [temp_arr > 5, temp_arr < 2]
choice_list = [temp_arr * 2, temp_arr + 100]

#np.select(조건식 리스트, 결과값 리스트, default = )
np.select(cond_list, choice_list, default = temp_arr)

array([100, 101,   2,   3,   4,   5,  12,  14,  16,  18])

## Reshape
 - 배열의 차원 또는 크기를 바꿈
 - 곱셈이 중요

In [48]:
import numpy as np
temp_array = np.ones((3,4))
print(temp_array.shape)
print(temp_array)

(3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


- 값을 임으로 바꿔서 순서를 확인바란다.

In [57]:
temp_array= random.randint(100, size = (3,1,4))
temp_array

array([[[34, 28, 61, 38]],

       [[49, 30, 47, 52]],

       [[78, 13, 72, 62]]])

- 3개의 4열을 만들었다. 그렇기에 아래도 12의 공배수로 적어줘야 된다.

In [58]:
after_reshape = temp_array.reshape(2,2,3)
print(after_reshape.shape)
print(after_reshape)

(2, 2, 3)
[[[34 28 61]
  [38 49 30]]

 [[47 52 78]
  [13 72 62]]]


- (2,2,?)를 했을 때 나머지 내용을 모르겠으면 (-1)을 적어주면 편하다.

In [59]:
after_reshape = temp_array.reshape(2,2,-1)
print(after_reshape.shape)
print(after_reshape)

(2, 2, 3)
[[[34 28 61]
  [38 49 30]]

 [[47 52 78]
  [13 72 62]]]


## 브로드 캐스팅
- 서로 다른 크기의 배열을 계산할 때의 기본적인 규칙을 의미

## 판다스

In [62]:
import pandas as pd
print(pd.__version__)

1.3.5


In [64]:
temp_dict = {
    'col1' : [1,2],
    'col2' : [3,4]
    }
df = pd.DataFrame(temp_dict)
print(df)
print(type(df))    

   col1  col2
0     1     3
1     2     4
<class 'pandas.core.frame.DataFrame'>


## 구글 드라이브 연동 

In [65]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [68]:
DATA_PATH= '/content/drive/MyDrive/Colab Notebooks/Human_ai/Basic/Chapter 3. pandas/data/'
print(DATA_PATH + 'Lemonade2016.csv')

lemonade  = pd.read_csv(DATA_PATH + 'Lemonade2016.csv')
#covid_df = pd.read_csv(DATA_PATH + 'owid-covid-data.csv')

lemonade.info()

/content/drive/MyDrive/Colab Notebooks/Human_ai/Basic/Chapter 3. pandas/data/Lemonade2016.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Date         31 non-null     object 
 1   Location     32 non-null     object 
 2   Lemon        32 non-null     int64  
 3   Orange       32 non-null     int64  
 4   Temperature  32 non-null     int64  
 5   Leaflets     31 non-null     float64
 6   Price        32 non-null     float64
dtypes: float64(2), int64(3), object(2)
memory usage: 1.9+ KB
