## 라이브러리 불러오기
- numpy 라이브러리를 불러온다. 

In [1]:
import numpy as np
print(np.__version__)

1.19.5


# 배열 생성의 다양한 방법들

- 모두 0으로 채운다. 

In [3]:
# 0으로 채운다.
temp_arr = np.zeros((2, 3))
temp_arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

- 모두 1로 채운다. 

In [6]:
# 
temp_arr = np.ones((3, 2, 2))
temp_arr

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

- 임의의 상수값으로 채운다. 

In [10]:
# 
temp_arr = np.full((3, 2), fill_value=1.5)
temp_arr

array([[1.5, 1.5],
       [1.5, 1.5],
       [1.5, 1.5]])

- 이번에는 최소 및 최대 숫자의 범위를 정해두고 구간별로 값을 생성하는 코드를 작성한다. 

In [12]:
#
temp_arr = np.linspace(5, 10, num = 30)
temp_arr

array([ 5.        ,  5.17241379,  5.34482759,  5.51724138,  5.68965517,
        5.86206897,  6.03448276,  6.20689655,  6.37931034,  6.55172414,
        6.72413793,  6.89655172,  7.06896552,  7.24137931,  7.4137931 ,
        7.5862069 ,  7.75862069,  7.93103448,  8.10344828,  8.27586207,
        8.44827586,  8.62068966,  8.79310345,  8.96551724,  9.13793103,
        9.31034483,  9.48275862,  9.65517241,  9.82758621, 10.        ])

- 반복문 시, 자주 사용하는 배열을 작성한다. 

In [15]:
#
temp_arr = np.arange(1, 11, 3)
temp_arr

array([ 1,  4,  7, 10])

- 이번에는 임의의 난수 생성을 확인한다. 

In [22]:
#
import numpy as np
np.random.seed(42)
np.random.rand()

0.3745401188473625

- 랜덤 배열을 생성한다. (Integer)




In [28]:
# 
x = np.random.randint(100, size = (5))
print(x)

[57 21 88 48 90]


In [29]:
#
x = np.random.randint(100, size = (2, 5))
print(x)

[[58 41 91 59 79]
 [14 61 61 46 61]]


- 랜덤 배열을 생성한다. (Floats)

In [31]:
# 
x = np.random.rand(2, 5)
print(x)

[[0.30461377 0.09767211 0.68423303 0.44015249 0.12203823]
 [0.49517691 0.03438852 0.9093204  0.25877998 0.66252228]]


# 배열 연산
- 간단한 사칙 연산을 구현한다. 

In [32]:
# 
array_01 = np.array([1,2,3])
array_02 = np.array([10,20,30])

array_01 + array_02

array([11, 22, 33])

In [33]:
#
newArr = np.add(array_01, array_02)
print("덧셈:", newArr)

덧셈: [11 22 33]


In [34]:
#
newArr = np.subtract(array_01, array_02)
print("뺄셈:", newArr)

덧셈: [ -9 -18 -27]


In [35]:
# 
newArr = np.multiply(array_01, array_02)
print("곱셈:", newArr)

곱셈: [10 40 90]


In [37]:
# 나눗셈
newArr = np.divide(array_01, array_02)
print("나눗셈:", newArr)

나눗셈: [0.1 0.1 0.1]


In [38]:
# 거듭제곱
array_01 = np.array([1,2,3])
array_02 = np.array([1,2,3])

newArr = np.power(array_01, array_02)
print("거듭제곱:", newArr)

거듭제곱: [ 1  4 27]


# 소숫점 정렬

- 소숫점을 제거하는 코드를 작성한다. 

In [39]:
#
temp_arr = np.trunc([-1.23, 1.23])
print(temp_arr)

[-1.  1.]


In [40]:
#
temp_arr = np.fix([-1.23, 1.23])
print(temp_arr)

[-1.  1.]


- 임의의 소숫점 자리에서 반올림

In [49]:
# 
temp_arr = np.around([-1.2312314, 1.212343], 4)
print(temp_arr)

[-1.2312  1.2123]


In [50]:
#
temp_arr = np.around([-1.2312314, 1.212343], 4)
print(temp_arr)

[-1.2312  1.2123]


- 소수점 모두 내린다. 

In [52]:
#
temp_arr = np.floor([-1.2312314, 1.212343])
print(temp_arr)

[-2.  1.]


- 소수점 모두 올린다. 

In [53]:
#
temp_arr = np.ceil([-1.2312314, 1.212343])
print(temp_arr)

[-1.  2.]


# numpy.where
- 조건식

In [55]:
# 
temp_arr = np.arange(10)
temp_arr
# 5미만 0, 1, 2, 3, 4
# 5이상 * 10
np.where(temp_arr < 5, temp_arr, temp_arr * 10)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

# numpy.select
- 조건식 list

In [58]:
temp_arr = np.arange(10)
temp_arr

conditional_list = [temp_arr > 5, temp_arr < 3]
result_list      = [temp_arr,     temp_arr + 100]

np.select(conditional_list, result_list, default = 99999)

array([  100,   101,   102, 99999, 99999, 99999,     6,     7,     8,
           9])