## 라이브러리 불러오기
- numpy 라이브러리를 불러온다. 

In [ ]:
#

1.19.5


# 배열 생성의 다양한 방법들

- 모두 0으로 채운다. 

In [ ]:
#

array([[0., 0., 0.],
       [0., 0., 0.]])

- 모두 1로 채운다. 

In [ ]:
#

array([[1., 1., 1.],
       [1., 1., 1.]])

- 임의의 상수값으로 채운다. 

In [ ]:
#

array([[3, 3, 3],
       [3, 3, 3]])

- 이번에는 최소 및 최대 숫자의 범위를 정해두고 구간별로 값을 생성하는 코드를 작성한다. 

In [ ]:
#

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

- 반복문 시, 자주 사용하는 배열을 작성한다. 

In [ ]:
#

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

- 이번에는 임의의 난수 생성을 확인한다. 

In [ ]:
#

0.9583074314709589


- 랜덤 배열을 생성한다. (Integer)




In [ ]:
#

[91 77 60  8 80]


numpy.ndarray

In [ ]:
#

[[45 13 50 33 27]
 [12  7 24 11 47]]


numpy.ndarray

- 랜덤 배열을 생성한다. (Floats)

In [ ]:
#

[[0.05818837 0.3082783  0.94124133 0.14034383 0.44526366]
 [0.61193532 0.49678617 0.97177352 0.96675612 0.01879365]]


# 배열 연산
- 간단한 사칙 연산을 구현한다. 

In [ ]:
#

[11 22 33]


In [ ]:
#

덧셈:  [11 22 33]


In [ ]:
#

뺄셈:  [ -9 -18 -27]


In [ ]:
#

곱셈:  [10 40 90]


In [ ]:
# 나눗셈


나눗셈:  [0.1 0.1 0.1]


In [ ]:
# 거듭제곱


거듭제곱:  [ 1  4 27]


# 소숫점 정렬

- 소숫점을 제거하는 코드를 작성한다. 

In [ ]:
#

[-1.  1.]


In [ ]:
#

[-1.  1.]


- 임의의 소숫점 자리에서 반올림

In [ ]:
#

[-1.237  1.231]


In [ ]:
#

[-1.237  1.231]


- 소수점 모두 내린다. 

In [ ]:
#

[-2.  1.]


- 소수점 모두 올린다. 

In [ ]:
#

[-1.  2.]


# numpy.where
- 조건식

In [ ]:
#

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

# numpy.select
- 조건식 list

In [ ]:
#

array([100, 101,   0,   0,   0,   0,   6,   7,   8,   9])