# NumPy 기본 문법

## 리스트를 NumPy로 변환하기
- 먼저 라이브러리를 불러온다. 

conda 
virtualenv

파이썬 범용 언어
- 웹개발, 머신러닝, 딥러닝, GUI, 앱, 통계, 시각화 대시보드
- 버전 충돌 (별도의 격리된 환경 만듬)
- requirements.txt

In [2]:
import numpy as np
print(np.__version__)

1.21.6


- 1부터 10까지의 리스트를 만든 후 NumPy 배열로 변환하여 저장한다. 

In [4]:
temp = [1,2,3,4,5,6,7,8,9,10]
temp_array = np.array(temp)
print(temp) # 리스트
print(temp_array) # NumPy

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


- type(), len() 함수를 사용하여 배열의 기본 정보를 확인한다. 

In [5]:
type(temp_array)

numpy.ndarray

In [ ]:
len(temp_array)

10

- 첫번째 인수 1을 출력한다. 

In [6]:
temp_array[0]

1

- 숫자 7을 출력한다. 

In [7]:
temp_array[6]

7

- 마지막 숫자 10을 출력한다. 

In [8]:
temp_array[9]

10

In [9]:
temp_array[-1]

10

- NumPy를 사용하여 기초 통계 함수를 사용해본다. 

In [ ]:
np.mean(temp_array)

5.5

## 사칙 연산
- 이번에는 임의의 수학 점수와 영어 점수를 합산하는 코드를 작성한다. 
- 그런데, List를 연산하면 원하는 결괏값이 나타나지 않는다. 
- 따라서, 리스트를 배열로 변환해야 한다. 

In [11]:
math_scores    = [90, 80, 88, 75, 85]
english_scores = [90, 100, 88, 80, 85]

math_scores + english_scores

[90, 80, 88, 75, 85, 90, 100, 88, 80, 85]

In [12]:
math_scores = [90, 80, 88, 75, 85]
english_scores = [90, 100, 88, 80, 85]

math_array = np.array(math_scores)
english_array = np.array(english_scores)

total_scores = math_array + english_array

- 최소 및 최대 값을 구한다. 

In [13]:
total_scores

array([180, 180, 176, 155, 170])

In [14]:
np.min(total_scores)

155

In [15]:
np.max(total_scores)

180

## 배열의 생성
- 배열은 크게 0차원부터 3차원까지로 구성한다. 

In [17]:
temp_arr = np.array(30)
print(type(temp_arr))
print(temp_arr.shape)

<class 'numpy.ndarray'>
()


In [19]:
# 1차원
temp_arr = np.array([1, 2, 3])
print(type(temp_arr))
print(temp_arr.shape)
print(temp_arr.ndim)

<class 'numpy.ndarray'>
(3,)
1


In [20]:
# 2차원
temp_arr = np.array([[1, 2, 3], [4, 5, 6]])
print(type(temp_arr))
print(temp_arr.shape)
print(temp_arr.ndim)

<class 'numpy.ndarray'>
(2, 3)
2


In [21]:
# 3차원 --> 이미지 
temp_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(type(temp_arr))
print(temp_arr.shape)
print(temp_arr.ndim)

<class 'numpy.ndarray'>
(2, 2, 3)
3


In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=2)

print(arr)
print('shape of array :', arr.shape)

[[1 2 3 4]]
shape of array : (1, 4)
